config/routes.rb
RestaurantApp::Application.routes.draw do

  devise_for :users

  resources :users do 
    resources :friendships
  end

  post '/users/search' => 'users#search', :as => :user_search

  post '/searches/search' => 'searches#search', :as => :search

  get '/restaurants/list' => 'restaurants#list', :as => :restaurant_list

  root 'users#index'
  

  resources :restaurants do
    resources :visits
    resources :future_visits
  end

  

  

end

app/models/friendship.rb
class Friendship < ActiveRecord::Base

	belongs_to :owner, :inverse_of => :friendships
	belongs_to :friend, :class_name => 'User'

	after_create :check_reciprocal_friendship


	protected

	def check_reciprocal_friendship
		reciprocal_friendship = Friendship.where(:owner_id => friend_id, :friend_id => owner_id).first

		if reciprocal_friendship
			reciprocal_friendship.update_column(:accepted, true)
			update_column(:accepted, true)
		end
		
	end

end

app/models/future_visit.rb
class FutureVisit < ActiveRecord::Base
	belongs_to :restaurant
	belongs_to :user



end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	validates :name,  :presence => true

	has_many :visits
	has_many :future_visits
	
	before_validation :fix_url_protocol

	validates_uniqueness_of :name, :case_sensitive => false


	# def average_rating
	# 	@restaurant.average_rating = @restaurant.visits.average(:rating).to_s
	# 	@restaurant.save
	# end


	protected

	def fix_url_protocol
		unless self.website[/^http:\/\//] || self.website[/^https:\/\//]
			self.website = 'http://' + self.website
		end
	end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :visits
  has_many :future_visits
  
  has_many :friendships, :foreign_key => :owner_id
  has_many :friends, :through => :friendships

  def friendship_status_with(user)
  	friendship = friendships.where(:friend_id => user.id).first
  	friendship.accepted? ? "Friend" : "Friendship pending"
  end

  def to_s
    name
  end
  
end

app/models/visit.rb
class Visit < ActiveRecord::Base
	
	validates :rating, :presence => true


	belongs_to :restaurant
	belongs_to :user


	# after_save :update_average_rating


#### I couldn't make this feature work yet without breaking other parts ####

	# def update_average_rating 
	# 	average_rating = Visit.average(:rating, :conditions => [ 'restaurant_id = ?', restaurant_id ] )
 #    restaurant = Restaurant.find(:first, restaurant_id)
 #    restaurant.average_rating = average_rating
 #    restaurant.save
	# 	end


	def to_s
		restaurant_id
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
   #Adding 'name' field for User and Devise
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation) }
  end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
	
  def create
    @user = User.find(params[:user_id])    
    current_user.friends << @user
	  redirect_to user_path(@user)
	end

end

app/controllers/future_visits_controller.rb
class FutureVisitsController < ApplicationController

  before_action :find_restaurant, :only => [:new, :create, :destroy, :recommend]


  ## I have this here, to show a new page, which will have a list of users I need to pick from.

  def new
		@future_visit = @restaurant.future_visits.new   
	end

  def index


  end


  def create
    @future_visit = @restaurant.future_visits.new 

    if params[:future_visit] && params[:future_visit][:user_id]
      @future_visit.user = User.find(params[:future_visit][:user_id])
      notice = "You've recommended this restaurant to #{@future_visit.user}"
    else
      @future_visit.user = current_user
      notice = "Restaurant successfully added to queue"
    end

    if @future_visit.save
      redirect_to restaurant_path(@restaurant), :notice => notice
    else
      render 'restaurant/show'
    end

  end


  def destroy
    @future_visit = FutureVisit.find(params[:id])
    @future_visit.destroy
    redirect_to restaurant_path(@restaurant)
  end 


  protected
  
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])    
  end


end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	before_action :find_restaurant, :only => [:show, :edit, :update, :destroy] 
	before_action :get_restaurants, :only => [:index, :list]


	def index
		
		
	end


	def list

	end


	def new
		@restaurant = Restaurant.new
	end


	def create
		@restaurant = Restaurant.new params.require(:restaurant).permit(:name, :website, :location)

		if @restaurant.save
			redirect_to restaurant_path(@restaurant)
		else
			render 'new'	
		end

	end


	def show

	end


  protected

  def permitted_attributes
    params.require(:restaurant).permit(:name, :website, :location)
  end


  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end


  def get_restaurants
  	@restaurants = Restaurant.all	
  end


end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
	
	def new
		
	end


	def search


		@users = User.where("name ilike?", "%#{params[:search]}%")
		@users = User.where("email ilike?", "%#{params[:search]}%")
		@restaurants = Restaurant.where("name ilike?", "%#{params[:search]}%")
	end




end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
	 	@user = User.find(params[:id])
  end

  def index
 	end

end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController

  before_action :find_restaurant, :only => [:new, :create]

	def new
		@visit = @restaurant.visits.new
	end


  def create
    @visit = @restaurant.visits.new params.require(:visit).permit(:rating, :review)
    @visit.user = current_user

    if @visit.save
      redirect_to restaurant_path(@restaurant), :notice => "Visit Successfully Saved"  
    else
      render 'new'
    end
    
  end


  protected
  
  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])    
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
	
	def render_stars(value)
		output = ''
		
		if (1..5).include?(value)
			value.times {output += '*'}
		end
		
		output
	
	end

end

app/views/future_visits/new.html.erb
<h2>Who would you like to recommend <%= @restaurant.name %> to?

<%= form_for [@restaurant,@future_visit]  do |f| %>
      	<% @future_visit.errors.full_messages.each do |msg| %>
  			<p class="text-warning"><%= msg %></p>
			<% end %>

      <div>

      <%= f.collection_select :user_id, current_user.friends, :id, :name, :class => 'dropdown-menu' %></div>
  
      
			</br>
    	<%= f.submit "Submit", :class => 'btn btn-primary' %>
			</br>



<% end %>

</br>
<p><%= link_to 'Back to Home', root_path %></p>

app/views/layouts/_footer.html.erb
<hr>

<div id ="footer" >
	<div class="container">	
	  <p class = "text-muted">Built and Barely Designed by Tracy Mu Sung</p>
	  <p class = "text-muted">If the details of any restaurant have changed, please submit a <a href="mailto:admin@moomumedia.com?Subject=Restaurant%20Update">change request</a></p>   
	 </div>
</div> 

app/views/layouts/_header.html.erb
<div class = "header">
  <ul class="nav nav-pills pull-right">
    <li><%= link_to "Restaurants", restaurant_list_path %></li>
   
    <% if current_user %>
  		<li><%= link_to 'My Profile', user_path(current_user) %></li>
      <li><%= link_to 'Settings', edit_user_registration_path(current_user) %></li>
      <li><%= link_to 'Sign out', destroy_user_session_path, :method => 'delete' %></li>
    	  
		<% else %>
			<li><%= link_to 'Sign in', new_user_session_path %> </li>
			<li><%= link_to 'Sign Up', new_user_registration_path %></li>
		<% end %>
  </ul>

  <span class = "navbar-form navbar-right">
    <%= form_tag search_path do %>
      <%= text_field_tag 'search' %>
      <%= submit_tag 'go'%>
    <% end %>
  </span>

  <% if current_user %>
    <span id = "logo_small"><%= link_to "Queue", user_path(current_user) %></span>
  <% else %>
    <span id = "logo_small"><%= link_to "Queue", root_path %></span>
  <% end %>
  
</div>

<hr>

<% if notice || alert %>
  <span class="alert alert-info"><%= notice %></span
  <span class="alert alert-info"><%= alert %></span>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RestaurantApp</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <link href="http://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
	<link href="http://fonts.googleapis.com/css?family=Cabin" rel="stylesheet" type="text/css">
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div id="wrap" class="container">

			<%= render "layouts/header" %>

			<%= yield %>
		</div>

		<%= render "layouts/footer" %>
		

</body>
</html>

app/views/restaurants/edit.html.erb
<h1>Add a New Restaurant</h1>

<%= form_for @restaurant do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>
  
      <%= f.label :website %>
      <%= f.text_area :website %>

      <%= f.label :location %>
      <%= f.text_area :location %>

    	<%= f.submit %>

<% end %>

app/views/restaurants/index.html.erb
<% if current_user %>

  <div class="row">
    
    <div class = "col-md-1">
    </div>
    
    <div class="col-md-5">
      <h2>Top Rated Restaurants</h2>
    </div>
    
    <div class="col-md-5">
      <h2>Recent's Activity</h2>
    </div>
  
  </div>

  <div class = "row">

    <div class = "col-md-1">
    </div>

    <div class = "col-md-5 ">
      <div class = "restaurant_list"> 
        <ul>
          <% @restaurants.first(5).each do |restaurant| %>
            <li><strong><%= link_to restaurant.name, restaurant_path(restaurant) %></strong></li>
            <%= restaurant.location %>
            <hr>
          <% end %>
        </ul>
      </div>
      <p><%= link_to 'See all', restaurant_list_path %></p>

    </div>


    <div class = "col-md-5">
      <h2>Friends</h2>

      <% current_user.friendships.where(:accepted => true).each do |friendship| %>
        <p><%= link_to friendship.friend.name, user_path(friendship.friend) %></br>
          <% friendship.friend.visits.each do | visit| %>
            <p>Recently to <%= visit.restaurant.name %></p>
          <% end %>



      <% end %>
      
    </div>
  </div>



<% else %>

  <div class = "jumbotron">

    <span id = "logo">Queue</span>

    <p class = "lead">Can’t think of where to eat? Always go to the same places?</br>
    Make every meal count with Queue</p>

    <%= link_to 'Sign Up', new_user_registration_path, :class => 'btn btn-success btn-lg' %> or <%= link_to 'Sign in', new_user_session_path, :class => 'btn btn-primary btn-lg' %>

  </div>



<% end %>

app/views/restaurants/list.html.erb
<div class = "row">
  <div class = "col-md-1">
  </div>
  <div class = "col-md-4">
    <h1>All Restaurants</h1>
  </br>
  </div>

  <div class = " col-md-4">
    <% if current_user %>
      <h3>Been somewhere not listed? </h3><%= link_to 'New Restaurant', new_restaurant_path, :class => 'btn btn-primary' %>
    <% else %>
      <h2><%= link_to 'Sign Up', new_user_registration_path, :class => 'btn btn-success' %> or <%= link_to 'Sign in', new_user_session_path, :class => 'btn btn-primary' %> </h2>
      To start building your Queue
    <% end %>
  </div>

</div>


<div class = "row">
  <div class = "col-md-1">
  </div>
  <div class = "col-md-8">
	  <div class = "restaurant_list">
		  <ul>
        <% @restaurants.order('name ASC').each do |restaurant| %>
          <li><strong><%= link_to restaurant.name, restaurant_path(restaurant) %></strong>  <%= restaurant.location %></li>
          <hr>
        <% end %>
  	  </ul>
    </div>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1>Add a New Restaurant</h1>

<%= form_for @restaurant  do |f| %>

	<% @restaurant.errors.full_messages.each do |msg| %>
  			<p class="text-warning"><%= msg %></p>
			<% end %>
      <div><%= f.label :name %></br>
      <%= f.text_field :name %></div>
  
      <div><%= f.label :website %> </br>
      <%= f.text_area :website %></div>

      <div><%= f.label :location %></br>
      <%= f.text_area :location %></div>
			</br>
    	<%= f.submit "Submit", :class => 'btn btn-primary' %>

<% end %>
</br>

<p>Back to <%= link_to "home", root_path %></p>

app/views/restaurants/show.html.erb
<div class = "row">
	<div class = "col-md-1">
  </div>
	
	<div class = "col-md-5">
		<h1><%= @restaurant.name %></h1>
		<strong>Website: </strong><%= link_to @restaurant.website, @restaurant.website, :target => 'blank' %> </br>
		<strong>Location: </strong><%= @restaurant.location %> </br>
		<% if current_user %>
			<strong>Average Rating:</strong> <%= @restaurant.visits.average("rating")%></br>
			</br>
			<h3>Reviews by your friends</h3>

			<% @restaurant.visits.each do |visit| %>			
				<strong><%= visit.user.name %></strong>,  
				<em><%= visit.created_at.strftime("%d %b. %Y") %></em>
				<p>Rated: <%= render_stars(visit.rating) %></br>
				"<%= visit.review %>"</p>
				<hr>
			<% end %>
		<% end %>
		</br>
		
	</div>
	<% if current_user %>
		<div class = "col-md-5">
<!-- button for later, only show if you haven't been here -->

<!-- e.g. if current_user.visit.exists?(@restaurant)...? but not quite like that. --> 

			<% if current_user.visits.exists?(:restaurant_id => @restaurant.id) %>

				You've been to <%= @restaurant.name %> </p>

			<% else %>
				</br>
				</br>
	 			<%= link_to "I've been here", new_restaurant_visit_path(@restaurant), :class => 'btn btn-primary' %>
				</br>
			
			<% end %>

			<hr>
<!-- If restaurant is not in your queue, show this -->
<!-- so I need another if statement here -->

			<% if future_visit = current_user.future_visits.where(:restaurant_id => @restaurant.id).first %>
				<p><%= @restaurant.name %> is in your Queue  <%= link_to "Remove from Queue", restaurant_future_visit_path(@restaurant, future_visit), :confirm => 'Are you sure?', method: :delete %></p>

			<% else %>

				<p>Want to go here in the future?</p>
				<%= link_to "Add to Queue", restaurant_future_visits_path(@restaurant), :method => 'post', :class => 'btn btn-primary' %>
				</br>
			<% end %>
			<hr>

			<p>Recommend <%= @restaurant.name %> to a friend </p>
			<%= link_to "Recommend", new_restaurant_future_visit_path(@restaurant), :class => 'btn btn-primary' %>

		<!-- Here I think I should put a drop down with all your friends in it -->
			</br>

		</div>

	</div>

	
	<% else %>
		</br>
		</br>
		<%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign Up', new_user_registration_path %> to build a Queue or see friends' activity.</p>
	
	<% end %>

</div>

app/views/searches/search.html.erb
<h1>Your Search Results for <%= params[:search] %></h1>
<ul>
  <% @users.each do |user| %>
  	<li><%= link_to "#{user.name}", user_path(user)  %></li>
  <% end %>
	<% @restaurants.each do |restaurant| %>
  	<li><%= link_to "#{restaurant.name}", restaurant_path(restaurant)  %></li>
  <% end %>

</ul>

app/views/users/_user_data.html.erb
<div class = "row">
	<div class = "col-md-1">
  </div>

	<div class = "col-md-4">

		<h2>Queued Restaurants</h2>
		<% if @user.future_visits.exists? %>

			<ul>
				<% @user.future_visits.each do |future_visit| %>
					<li><%= link_to future_visit.restaurant.name, restaurant_path(future_visit.restaurant) %> </li>
				<% end %>
			</ul>

		<% else %>
			<% if @user == current_user %>
				<p>Nothing in your Queue yet? </p>
				<%= link_to "Browse Restaurants", restaurant_list_path(@restaurant), :class => 'btn btn-primary' %>
			<% else %>
				<p><%= @user.name %> doesn't have any restaurants Queued yet </p>	
				<%= link_to "Recommend a Restaurant", restaurant_list_path(@restaurant), :class => 'btn btn-primary' %>
			<% end %>
		<% end %>

		<h2>Visited Restaurants</h2>
		<% if @user.visits.exists? %>
			<ul>
				<% @user.visits.each do |visit| %>
					<li><%= link_to visit.restaurant.name, restaurant_path(visit.restaurant) %></li>
				<% end %>
			</ul>

		<% else %>
			<% if @user == current_user %>
				<p>You haven't registered any visits yet.</p>
			<% else %>
				<p><%= @user.name %> hasn't registered any visits yet.</p>	
			<% end %>
		<% end %>

	</div>
	<div class = "col-md-4">

		<h2>Friends</h2>
		<% if @user.friendships.exists? %>
			<ul>
				<% @user.friendships.where(:accepted => true).each do |friendship| %>
					<li><%= link_to friendship.friend.name, user_path(friendship.friend) %> </li>
				<% end %>
			</ul>
		<% else %>
			<% if @user == current_user %>
				<p>Use the search box above to find your friends</p>
			<% end %>
		<% end %>

	</div>
</div>

app/views/users/index.html.erb
	<div class = "row">
		<% if current_user %>
 		<div class = "col-md-1">
  	</div>
		<div class = "col-md-3">

			<% @user = current_user %>
			<H1><%= @user.name %></H1>
		</div>
	</div>
<!-- Only logged in users can see this page information -->
	<div class = "row">
		<div class = "col-md-1">
  	</div>



	<!-- Display at the top depends on whether this is your own user page or someone elses -->

		<% if current_user == @user  %>
	
			<% if Friendship.exists?(:friend_id => current_user.id, :accepted => nil) %>
			
				<p>You have friend requests from </p>
				<% Friendship.where(:friend_id => current_user.id, :accepted => nil).each do |friendship| %>
					<div class ="col-md-1"></div>
					<%= link_to User.find(friendship.owner_id).name, user_path(friendship.owner_id) %> | <%= link_to 'Accept Friendship', user_friendships_path(User.find(friendship.owner_id)), :method => 'post'   %> </br>
					<% end %>
				
			<% end %>
			<hr>
			<%= render "users/user_data" %>

		<% elsif @user.friendships.exists?(:friend_id => current_user.id, :accepted => true) %>
			<p> You are friends with <%= @user.name %></p>
			<hr>
			<%= render "users/user_data" %>

		<% else %>

			<% if current_user.friendships.exists?(:friend_id => @user.id) %>
				<p><%= current_user.friendship_status_with(@user) %>
			<% else %>
				<p><%= link_to 'Send a friend request', user_friendships_path(@user), :method => 'post'  %> to see <%= @user.name %>'s Queue </p>
			<% end %>
		<% end %>

	<% else %>
	
		<div class = "jumbotron">

    <span id = "logo">Queue</span>

    <p class = "lead">Can’t think of where to eat? Always go to the same places?</br>
    Make every meal count with Queue</p>

    <%= link_to 'Sign Up', new_user_registration_path, :class => 'btn btn-success btn-lg' %> or <%= link_to 'Sign in', new_user_session_path, :class => 'btn btn-primary btn-lg' %>
  	</div>
<% end %>  
  </div>
		

app/views/users/search.html.erb
<h1>Your Search Results for <%= params[:search] %></h1>
<ul>
  <% @users.each do |user| %>
  	<li><%= link_to "#{user.name}", user_path(user)  %></li>
  <% end %>
</ul>

app/views/users/show.html.erb
<div class = "row">
 	
 	<div class = "col-md-1">
  </div>
	
	<div class = "col-md-3">
		<H1><%= @user.name %></H1>
	</div>

</div>
<!-- Only logged in users can see this page information -->
<div class = "row">
	<div class = "col-md-1">
  </div>

	<% if current_user %>

	<!-- Display at the top depends on whether this is your own user page or someone elses -->

		<% if current_user == @user  %>
	
			<% if Friendship.exists?(:friend_id => current_user.id, :accepted => nil) %>
			
				<p>You have friend requests from </p>
				<% Friendship.where(:friend_id => current_user.id, :accepted => nil).each do |friendship| %>
					<div class ="col-md-1"></div>
					<%= link_to User.find(friendship.owner_id).name, user_path(friendship.owner_id) %> | <%= link_to 'Accept Friendship', user_friendships_path(User.find(friendship.owner_id)), :method => 'post'   %> </br>
					<% end %>
				
			<% end %>
			<hr>
			<%= render "users/user_data" %>

		<% elsif @user.friendships.exists?(:friend_id => current_user.id, :accepted => true) %>
			<p> You are friends with <%= @user.name %></p>
			<hr>
			<%= render "users/user_data" %>

		<% else %>

			<% if current_user.friendships.exists?(:friend_id => @user.id) %>
				<p><%= current_user.friendship_status_with(@user) %>
			<% else %>
				<p><%= link_to 'Send a friend request', user_friendships_path(@user), :method => 'post'  %> to see <%= @user.name %>'s Queue </p>
			<% end %>
		<% end %>

	<% else %>
	
		<%= link_to 'Sign in', new_user_session_path %> or <%= link_to 'Sign Up', new_user_registration_path %> to view <%= @user.name %>'s activity</p>
		
	<% end %>
</div>

app/views/visits/new.html.erb
<h1>If you've been to <%= @restaurant.name %></h1>

<p>Help your friends out by rating and/or reviewing </p>

<div class = "row">
	<div class = "col-md-8">
		<%= form_for [@restaurant, @visit] do |f| %>

 			<% @visit.errors.full_messages.each do |msg| %>
  			<p class="text-warning"><%= msg %></p>
			<% end %>

			<Strong>Rate Your visit: </Strong></br>
      <%= f.radio_button(:rating, "1") %>
      <%= f.label :rating, 1 %>
			<%= f.radio_button(:rating, "2") %>
      <%= f.label :rating, 2 %>
      <%= f.radio_button(:rating, "3") %>
      <%= f.label :rating, 3 %>
      <%= f.radio_button(:rating, "4") %>
      <%= f.label :rating, 4 %>
      <%= f.radio_button(:rating, "5") %>
      <%= f.label :rating, 5 %>  </br>
    
      <%= f.label :review %></br>
      <%= f.text_area :review, :class => "form-control" %></br>
			</br>

		  <%= f.submit "Submit", :class => 'btn btn-primary' %>
		<% end %>
		</br>
		<%= link_to 'Go back', restaurant_path(@restaurant) %>

	</div>
</div>